spring:
  application:
    name: user-management
  jackson: 
    serialization.indent_output: true
    serialization.write_dates_as_timestamps: false
  profiles: 
    active: local
    
info: 
  project: 
    version: "@project.version@"

management:
  context-path: /application
jhipster:
    cors:
      allowed-origins: "*"
      allowed-methods: GET, PUT, POST, DELETE, OPTIONS
      allowed-headers: "*"
      exposed-headers:
      allow-credentials: true
      max-age: 1800
    swagger:
      default-include-pattern: /api/.*
      title: user management API
      description: user management API documentation
      version: 0.0.1
      terms-of-service-url:
      contact-name:
      contact-url:
      contact-email:
      license:
      license-url:
    security:
      client-authorization:
        client-id: user-management
server:
  tomcat:
    accesslog:
      enabled: true
      directory: /var/logs

uaa:
  web-client-configuration:
    # Access Token is valid for 1 hour
    access-token-validity-in-seconds: 3600
    # Refresh Token is valid for 7 days
    refresh-token-validity-in-seconds-for-remember-me: 604800
